### PR TITLE
Added reset option

### PR DESCRIPTION
**Pull request by richiepreece**
I added the ability to reset the captcha manually. This is helpful if the form was submitted correctly, and captcha was validated (making the response now invalid) but the form was invalid, requiring a re-response of the form to the server. Since the captcha response cannot be resubmitted, a reset of the form is required.

### CODE REVIEW

**Comment by clydetacoma** [comment]
+1

**Comment by dkarter** [comment]
+1

**Comment by vepasto** [comment]
Why wouldn't you use ```control.reset```?

**Comment by richiepreece** [comment]
I guess I didn't quite understand how that worked. Thanks!

**Pull request closed without merging**
